import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import RootProvider from "@/components/shared/providers/RootProvider";

const barlow = Barlow({
	variable: "--font-barlow",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${barlow.variable} font-barlow antialiased`}>
				<RootProvider>
					<NextTopLoader
						color="#3df3a9"
						shadow="0 0 10px #3df3a9,0 0 5px #3df3a9"
					/>
					<main>{children}</main>
				</RootProvider>
			</body>
		</html>
	);
}
