import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "../globals.css";
import NextTopLoader from "nextjs-toploader";
import RootProvider from "@/components/shared/providers/RootProvider";
import SidePanel from "@/components/shared/SidePanel";
import Alert from "@/components/shared/Alert";
import { ApiInstance } from "@/utils";
import DashboardHeader from "@/components/shared/DashboardHeader";
import { redirect } from "next/navigation";

const barlow = Barlow({
	variable: "--font-barlow",
	subsets: ["latin"],
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	let user: any = null;
	let countries = [];

	try {
		const res = await ApiInstance.get("/user/detail");
		user = res.data;

		const countriesRes = await ApiInstance.get("/api/get-countries");
		countries = countriesRes.data;
	} catch (error) {
		return redirect("/login");
	}

	return (
		<html lang="en">
			<body className={`${barlow.variable} font-barlow antialiased`}>
				<RootProvider user={user} countries={countries}>
					<NextTopLoader
						color="#00100a"
						shadow="0 0 10px #00100a,0 0 5px #00100a"
					/>
					<Alert />
					<main className="bg-[#F4F4F4] flex flex-col lg:flex-row w-full">
						<SidePanel />
						<section className="grow">
							<DashboardHeader />
							{children}
						</section>
					</main>
				</RootProvider>
			</body>
		</html>
	);
}
